version: '3'

volumes:
  db: {}
  redis: {}
  storage: {}
  meilisearch: {}

services:
  reverse_proxy:
    image: traefik
    restart: always
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web80.address=:80

      # Delete the following arguments to disable HTTPS
      - --entrypoints.web443.address=:443
      - --certificatesresolvers.letsencrypt=true
      - --certificatesresolvers.letsencrypt.acme.email=$LETSENCRYPT_EMAIL
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --entrypoints.web443.http.tls=true
      - --entrypoints.web443.http.tls.certresolver=letsencrypt
      - --entrypoints.web80.http.redirections.entrypoint.to=web443
    ports:
      - 80:80
      - 443:443 # Only needed for HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  app:
    image: paperbaseapp/paperbase
    env_file: .env
    volumes:
      - storage:/app/storage
    restart: always
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.paperbase.rule=Host(`$PAPERBASE_DOMAIN`)
  worker:
    image: paperbaseapp/paperbase
    env_file: .env
    volumes:
      - storage:/app/storage
    command: worker
    restart: always
  scheduler:
    image: paperbaseapp/paperbase
    env_file: .env
    volumes:
      - storage:/app/storage
    command: scheduler
    restart: always
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always
  meilisearch:
    image: getmeili/meilisearch:v0.19.0
    volumes:
      - meilisearch:/data
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
      MEILI_DB_PATH: '/data/database.ms'
      MEILI_NO_ANALYTICS: 'true'
      MEILI_NO_SENTRY: 'true'
